version: "3.8"

services:
  reiz-php-fpm:
    container_name: reiz-php-fpm
    platform: linux/amd64
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html/
    networks:
      - reiz-net

  redis:
    image: redis:alpine
    container_name: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    networks:
      - reiz-net

  db:
    image: mysql:5.7
    container_name: reiz-mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - reiz-net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    networks:
      - reiz-net

  dca-nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html/
    depends_on:
      - reiz-php-fpm
    networks:
      - reiz-net

networks:
  reiz-net:
    driver: bridge
    name: 'reiz-net'